### PR TITLE
Add comment about anonymous Alexa accounts

### PR DESCRIPTION
**Pull request by stezelMIT**
If your instructor gave you access to an anonymous Alexa account then you can skip this section on how to set up an Alexa Developer Account.

### CODE REVIEW

**Comment by stezelMIT** [comment]
I added the blurb "Please note: If your instructor gave you access to an anonymous Alexa account then you can skip this section on how to set up an Alexa Developer Account." so that kids doing Alexa with teacher created accounts do not waste time trying to create Alexa Dev accounts.

**Comment by stezelMIT** [comment]
@ewpatton Please advise: I tried to test my changes on alexa with tutorial URL as http://localhost:4000/yrtoolkit/yr/tutorials/Number_Guessing_Game.html
as I ususally do.  I am getting errors as seen below: 
Selims-MacBook-Pro-2:yrtoolkit selimtezel$ bundle exec jekyll serve
Configuration file: /Users/selimtezel/Documents/GitHub/yrtoolkit/_config.yml
            Source: /Users/selimtezel/Documents/GitHub/yrtoolkit
       Destination: /Users/selimtezel/Documents/GitHub/yrtoolkit/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 8.265 seconds.
 Auto-regeneration: enabled for '/Users/selimtezel/Documents/GitHub/yrtoolkit'
    Server address: http://127.0.0.1:4000/yrtoolkit/
  Server running... press ctrl-c to stop.
[2022-09-01 13:46:19] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01?\x03\x03?7E?\t??\x06 pi]??i???0??r????C.\x00?( ??}?β????TE??h???}\x1F??\r????\x02W\x1A??\x00 zz\x13\x01\x13\x02\x13\x03?+?/?,?0̨̩?\x13?\x14\x00?\x00?\x00/\x005\x01\x00\x01?'.
[2022-09-01 13:46:19] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01?\x03\x03\x05H?S`???*\b1?̝?Κ???!??a\x01)?????z ????????\x18>??b\x04??'Z??5u?\x17簔\x02\x13?\x00 ZZ\x13\x01\x13\x02\x13\x03?+?/?,?0̨̩?\x13?\x14\x00?\x00?\x00/\x005\x01\x00\x01?ZZ\x00\x00\x00\x00\x00\x0E\x00\f\x00\x00\tlocalhost\x00\x17\x00\x00?\x01\x00\x01\x00\x00'.

**Comment by ewpatton** [comment]
@stezelMIT My guess is that you are using the Alexa server over HTTPS, so App Inventor tries to load the tutorial over HTTPS as well. You can temporarily switch to http://alexa.appinventor.mit.edu for testing the tutorial.

**Comment by stezelMIT** [comment]
@ewpatton Haha!  That was it much thanks.  If this looks good to you kindly approve PR.  I will need to revise the AI tutorial site today to get ready for the NSF process.  Much thanks.

**Review by ewpatton — APPROVED** [review]

**Comment by ewpatton** [comment]
@stezelMIT I think this is a good short term solution. I have an idea for a slightly more sophisticated solution where we hide the instructions given a specific signal from App Inventor. Implementing that will take a little bit of time though. Hilah and Garrett have also asked whether we could do a space-themed variation for the hello world tutorial called Hello Moon. It seems like it should be fairly straightforward to copy the current tutorial and make the necessary modifications.

**Pull request merged**
