### PR TITLE
Reconcile tabHandler.js references

### LINKED ISSUE #67: Removal of "HowTo" tab in header messes up tutorials
At the top of each tutorial, there are 2 tabs - left is label "App Guide" and the right is usually "How To". If you remove the div in your tutorial for the "How To" tab, your entire tutorial is messed up. Your separate tutorialContent divs that usually show up as separate pages that are steps in the sequence of instructions for the tutorial end up as one single html page.

It would be good to be able to eliminate those tabs at the top (potentially both) if you don't have any "how to" pages for a particular tutorial.

### PR DESCRIPTION
**Pull request by ewpatton**
This change moves the shared script tabHandler.js to a shared script directory and fixes two undefined element errors when removing the Youth Mobile Power and How To tabs from the top of the different pages. I've removed the tabs from the AI and Malden pages since they aren't Youth Mobile Power related, but I can restore them if desired.

Fixes #67 

Change-Id: I03b5354144afe6800b0508c5e6821f9d82d4443e

### CODE REVIEW

**Comment by stezelMIT** [comment]
I was trying to remove the “How To” in the latest RPS YR media tutorial and it completely was messing the tabbed page structure (the Next buttons would disappear and all content would be dumped to a single page), so I left everything untouched.  Is this PR fixing this issue?  Out of curiosity what motivated this change as I had not yet post a request.
Thank you
Selim

**Comment by ewpatton** [comment]
@kdclang I've gone ahead and removed all tab sections where the "how to" tab had no text. I left the ones where "How To" is actually specified. If you'd like me to remove more let me know. I also reconciled the other scripts into the top level scripts directory.

@stezelMIT You can check out this branch using GitHub Desktop and test it using the same technique you'd use to evaluate changes that you and Karen make to the YR tutorials.

**Comment by kdclang** [comment]
@ewpatton The highest level directory has an index.html. While most of the tutorials linked are outdated (looks like they were copied at one point from subdirectories) and incomplete, the how to that shows up if you open that index file could be really useful (and makes more sense than the YR how-to tab, which is really more like "help with expansion suggestions". I was wondering how we might incorporate that how-to tab with its contents in all the tutorials. But I think the change you are making now in itself is going to help by removing the how-to tab when it's not needed.

**Comment by stezelMIT** [comment]
My humble apologies, I only have been reviewing Karen’s specific sidebar tutorials (Malden, AI) and I am not sure how to test this branch which seems to span many files etc.  Perhaps tomorrow during the Ed meeting Karen will give me pointers how to do this.
Thank you
Selim

PS: I have been working on the RPS tutorial when Evan was making these changes.  How would I know if there are any conflicts?

**Comment by ewpatton** [comment]
@kdclang Thanks for pointing out that it breaks when accessed from the top level index.html. I've been deep linking into the tutorials since that's what the TutorialURL does, and that seemed to be working okay. Unfortunately, the index.html is doing something very weird which is dynamically loading and replacing the content of the page rather than just linking directly. The latter would probably be cleaner, but I'll have to look at how index.html is constructed. If you try tutorials in App Inventor, substituting localhost:8000 for appinventor.mit.edu/yrtoolkit, do you see similar problems with the Connect feature?

**Comment by kdclang** [comment]
Yes, Connect App tab breaks it at every level. YR, Malden, etc. I wouldn't
worry about the main level index.html not working, as it hasn't for awhile,
and isn't really used.

**Comment by kdclang** [comment]
Checked again after talking to @stezelMIT, cleared cache and all look good now.

**Pull request merged**
