### PR TITLE
Fix bad URL to tutorialPage.js in DIYBookClub

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Iee1aa890828ec8f85cfeb0e042c1b0ec3b524960

### CODE REVIEW

**Comment by stezelMIT** [comment]
Is this an issue only in the DIY Book Club?  In most YR tutorials, we just copy paste these initial lines.  BTW how did you notice this?

**Comment by ewpatton** [comment]
@stezelMIT There was an issue reported on the community: https://community.appinventor.mit.edu/t/buttons-in-diy-book-club-introduction-tutorial-arent-working/6529/5?u=ewpatton

I did a grep through the code base looking for "../../.." and only turned up a couple of things that seem to make sense. This seems to be the only occurrence of this problem, but it might not hurt to check the other tutorials.

**Comment by stezelMIT** [comment]
This did not happen before, do you know how that extra /../ was added without anyone noticing?  Did we move things out of their folders recently?

**Comment by stezelMIT** [comment]
I checked an only DIY amongst the YR tutorials has that bizarre sidebar tabs mess up.
I vaguely recall earlier there was a CSS change that you or Karen initiated, I wonder if this is related to that.

**Comment by stezelMIT** [comment]
I also recently noticed, even though this probably has nothing to do with the PR, that whenever you hover over a YR tutorial image it fades off and a generic image icon shows up -what you would see if the image link was broken-which really looks bad.  Does anyone know what might have prompted this new image hover property change?

**Comment by ewpatton** [comment]
@stezelMIT Thanks for pointing that out. #84 should fix that issue.

**Pull request merged**
